### ISSUE TITLE
Define an alternative path for resources

### ISSUE THREAD

**Issue by hiukky** [adonisjs/view#1]
Regarding the render method in ctx .. is there any parameter or setting to change the default path?

```js
├── app
│   ├── Core
│   │   ├── resources
```

For example I'm trying to create a structure with adonis where I can define my business rules, helpers, middlewares, resources and can reference them from this path intention is to have a code shared with another api Adonis without duplicity because it's just a part of the project.. would there be any way I could define this?

would be interesting because in the core of my application would be most of the project for both APIs.

**Comment by thetutlage** [comment]
Will be fixed with newer release of AdonisJs (ie v5), it allows customizing all paths
