### ISSUE TITLE
bug singleton view register provider 

### ISSUE THREAD

**Issue by menphurk** [adonisjs/view#11]
I use V5 but error Cannot read property 'singleton' of undefined then i not start node ace serve --watch

![21-4-2564 15-08-53](https://user-images.githubusercontent.com/16397672/115519701-a2da6700-a2b3-11eb-958d-85b0ef9974b2.png)

**Comment by menphurk** [comment]
this file .adonisrc.json ---->
{
    "typescript": true,
    "commands": [
        "./commands",
        "@adonisjs/core/build/commands",
        "@adonisjs/repl/build/commands",
        "@adonisjs/lucid/build/commands",
        "@adonisjs/mail/build/commands"
    ],
    "exceptionHandlerNamespace": "App/Exceptions/Handler",
    "aliases": {
        "App": "app",
        "Config": "config",
        "Database": "database",
        "Contracts": "contracts"
    },
    "preloads": [
        "./start/routes",
        "./start/kernel"
    ],
    "providers": [
        "./providers/AppProvider",
        "@adonisjs/core",
        "@adonisjs/lucid",
        "@adonisjs/auth",
        "@adonisjs/mail",
        "@adonisjs/view"
    ],
    "aceProviders": [
        "@adonisjs/repl"
    ],
    "metaFiles": [{
        "pattern": "resources/views/**/*.edge",
        "reloadServer": false
    }]
}

**Comment by thetutlage** [comment]
Can you please share the `package.json` file and also format the codeblocks. Here's the link to the Markdown guide https://guides.github.com/features/mastering-markdown/

**Comment by thetutlage** [comment]
Issue doesn't adhere to the guidelines of creating a proper issue.

1. Make sure that you are only reporting bugs or submitting feature requests on Github.
2. In case of feature requests, please be descriptive and explain how this feature helps a broader audience and not just you.

If you are not submitting a bug and neither a feature request, then please use the [discussion threads](https://github.com/adonisjs/core/discussions)

**In any case, issues which are not descriptive enough will be closed. Please respect our time.**
