### ISSUE TITLE
csrfFiled() not available when edge template redered within a Controller

### ISSUE THREAD

**Issue by pflirae** [adonisjs/view#12]
## Package version
 "devDependencies": {
    "@adonisjs/assembler": "^5.1.1",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.24.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-adonis": "^1.3.1",
    "eslint-plugin-prettier": "^3.3.1",
    "pino-pretty": "^4.7.1",
    "prettier": "^2.2.1",
    "typescript": "4.2",
    "youch": "^2.2.1",
    "youch-terminal": "^1.1.0"
  },
  "dependencies": {
    "@adonisjs/auth": "^8.0.0",
    "@adonisjs/core": "^5.1.6",
    "@adonisjs/fold": "^8.1.0",
    "@adonisjs/lucid": "^14.0.0",
    "@adonisjs/mail": "^7.1.1",
    "@adonisjs/redis": "^7.0.2",
    "@adonisjs/repl": "^1.1.6",
    "@adonisjs/session": "^6.0.3",
    "@adonisjs/shield": "^7.0.1",
    "@adonisjs/view": "^6.0.1",
    "luxon": "^1.26.0",
    "mysql2": "^2.2.5",
    "phc-argon2": "^1.1.0",
    "proxy-addr": "^2.0.6",
    "recaptcha2": "^1.3.3",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "wkhtmltox": "^1.1.4",
    "xlsx": "^0.16.9"

## Node.js and npm version
npm - 7.12.1
node - 14.16.1

## Sample Code (to reproduce the issue)
The edge file (login.edge)
![image](https://user-images.githubusercontent.com/9519459/118065549-25ae8900-b36b-11eb-93a8-3da78ebb1cf8.png)

The routes.ts file
![image](https://user-images.githubusercontent.com/9519459/118065616-41b22a80-b36b-11eb-9649-1d6a2365328c.png)

The controller file
![image](https://user-images.githubusercontent.com/9519459/118065665-568ebe00-b36b-11eb-89d2-e47eac2c680b.png)

## BONUS (a sample repo to reproduce the issue)
When the base route / is called from a browser, the result is:
![image](https://user-images.githubusercontent.com/9519459/118065795-92c21e80-b36b-11eb-8f4f-3775012ab683.png)

if you uncoment the first route, and comment the second, all goes fine, so the conclusion is that there are some problem to access the csrfFiled() function when the render is done from a Controller.

**Comment by thetutlage** [comment]
You should be using the `ctx.view` and not the View module directly as shown in the docs https://docs.adonisjs.com/guides/views/introduction#basic-example

**Comment by pflirae** [comment]
Thanks, question solved.
