### ISSUE TITLE
Cannot use variable without reassignment

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/view#16]
When rendering, a state with `youtubeUrl` variable is passed to the template. I can render it:
```
{{ youtubeUrl }}
```

But, if I try usse it like  JS variable then I get fail
```
{{ new URL(youtubeUrl).pathname }} // 500: youtubeUrl is not defined
@set('obj',  new URL(youtubeUrl)) // 500: youtubeUrl is not defined
```

As a workaround, I have to reassign this variable to itself or another variable
```
@set('youtubeUrl', youtubeUrl)

{{ new URL(youtubeUrl).pathname }} // ok
@set('obj',  new URL(youtubeUrl)) // ok
```

## Package version
    "@adonisjs/core": "5.7.5",
    "@adonisjs/view": "6.1.3",

## Node.js and npm version
8.3.1

**Comment by thetutlage** [comment]
Closed in favor of https://github.com/edge-js/parser/issues/21

**Comment by thetutlage** [comment]
It has been fixed in the latest release of the `@adonisjs/view@6.1.4` package. Here's the related commit https://github.com/edge-js/parser/commit/a83127470758994f2d8c842b9e9bc93a7dc7c4ac
