### ISSUE TITLE
Rendering bug with caching enabled

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/view#17]
## Package version
    "@adonisjs/core": "5.7.6",
    "@adonisjs/view": "6.1.4",

## Node.js and npm version
node: v16.14.0
npm: 8.3.1

## Sample Code (to reproduce the issue)
I have two pages: one for [creating](https://github.com/cawa-93/adoins-issue-htmlHeadTitle/blob/d2bbd0f73593136c6005aa5e37df7dde6eacbaab/resources/views/create.edge) links and other one for [editing](https://github.com/cawa-93/adoins-issue-htmlHeadTitle/blob/d2bbd0f73593136c6005aa5e37df7dde6eacbaab/resources/views/edit.edge).

Both pages use the same layout. The peculiarity of this layout is that it is based on two variables:
`title` for `<title>` tag and `headerTitle` for `<h1>` tag. headerTitle is optional and contain HTML.

https://github.com/cawa-93/adoins-issue-htmlHeadTitle/blob/d2bbd0f73593136c6005aa5e37df7dde6eacbaab/resources/views/header.edge#L1

If caching is enabled, I see incorrect rendering of these variables.

## Steps to reproduce the issue
1. Clone [repo](https://github.com/cawa-93/adoins-issue-htmlHeadTitle).
2. Run it with `NODE_ENV=production` and `CACHE_VIEWS=true`.
3. Go to http://127.0.0.1:3333/create first and THEN go to http://127.0.0.1:3333/edit . Expected `<h1>` will be equal `headerTitle` but actual it's equal `title`.

Another case:
1. Restart server.
3. Go to http://127.0.0.1:3333/edit first and THEN go to http://127.0.0.1:3333/create. Expected `<h1>` will be equal `title` but actual page crash with error: `Error: headerTitle is not defined`

**Comment by thetutlage** [comment]
Seems a valid bug. I think partials should be cached, since they share the state of the parent template

**Comment by thetutlage** [comment]
Fixed in https://github.com/edge-js/edge/commit/ad2ceab6cf0ad6163811062cef937d40c5d75af1
