### ISSUE TITLE
Add prebuilt modifiers to hooks

### ISSUE THREAD

**Issue by enxoco** [adonisjs/view#2]
This isn't a bug but a feature request so feel free to tell me i'm in the wrong place.  Would you be open to the idea of adding some prebuilt content modifiers to the framework?  I have been playing around with Statamic a lot lately and one of the things that I really appreciate about it is that they have taken some really common data manipulation methods and baked them into the framework.  I have been developing a fully custom eCommerce platform on top of Adonis for the past year now and I have had to write a lot of these little functions myself.  

An example would be formatting a date string a certain way or converting a string to currency.  I know a lot of this could be handling in controllers as well but thought it would be nice to have some already built.  I would be more than happy to work on bringing some in.  Here is an example from the Statamic documentation.

https://docs.statamic.com/modifiers/collapse_whitespace

**Comment by thetutlage** [comment]
Open for someone to pickup the issue and work on it

**Comment by enxoco** [comment]
@thetutlage I can start working on these this week, although I am a little lost as to where to add the code.

**Comment by thetutlage** [comment]
Hello @enxoco

Sure, the code will go inside https://github.com/edge-js/edge repo.

The helpers you want to add are called global methods in Edge and edge exposes an API for same https://github.com/edge-js/edge/blob/develop/src/Edge/index.ts#L109. 

What I suggest doing is.

1. Create a file that has all the globals
2. Register globals with the default instance of edge exported by the index file https://github.com/edge-js/edge/blob/develop/index.ts#L31

I believe, that's pretty much all required to add them. Also, it will be nice, if you can first share a list of globals you are interested in adding

**Comment by enxoco** [comment]
@thetutlage Thanks for that.  That's what I thought, but just wanted to be sure.  I have added globals to that file previously for projects I have worked on.  I will start digging through it this week and share a list of ideas.

**Comment by thetutlage** [comment]
Closing, since not actionable for now. Re-open, when you want to work on it
