### ISSUE TITLE
global view not working for dynamic data update

### ISSUE THREAD

**Issue by jualahmed** [adonisjs/view#23]
## Prerequisites
i am trying to fatch data form databace and set the data to view but the update data are not getings untile restart the server 

## Package version
"@adonisjs/view": "^6.2.0",
"@adonisjs/core": "^5.9.0",

## Node.js and npm version
node 16+

## Sample Code (to reproduce the issue)
(async () => {
  try {
    const brand = await Brand.first();
    View.global('brand', brand ? brand : null);
  } catch (error) {
    return error;
    console.error('Error fetching brand data:', );
    // Handle the error as needed
  }
})();

**Comment by RomainLanz** [comment]
Hey @jualahmed! 👋🏻 

Please, write a proper reproduction code and push it inside a repository, it will be easier for us to understand your issue.

**Comment by jualahmed** [comment]
```typescript
(async () => {
  try {
    const brand = await Brand.first();
    View.global('brand', brand ? brand : null);
  } catch (error) {
    return error;
    // Handle the error as needed
  }
})();
``` 
**This is the code i write for make a global data call brand** 

```html
        <img src="/uploads/{{ brand.logo }}">
        <span>{{ brand.name }}</span>
``` 
**this is the code i write to print the data in .edge.**

i make it global so i can access it anywhere . the data is dynamic and it's coming from database. the code work find but the issue is when i update the data from database the data change but view still show the old data. only update view data when i restart the server

**Comment by RomainLanz** [comment]
1. This is not a repository with the minimum amount of code to reproduce the issue.
2. You are not defining the variable `brand` correctly. You created a global reference that will **never** change until you restart the server. Please [follow the documentation](https://docs.adonisjs.com/guides/views/data-flow#globals) to set view globals properly.

**Comment by jualahmed** [comment]
i read the documentation but there is no way to make global view with dynamic data preloaded with run time when i change the data from database after run the app it's not work ( still show old data ) when i rerun it's only update. so i am asking is there any soluation ?  my goal i need to change the data after run the app

**Comment by RomainLanz** [comment]
As said, you are doing it wrong by using a global variable. `View.global()` want a callback that will be executed **each** time you call it.

```ts
View.global('brand', function () {
  return Brand.first()
});
```

**Comment by jualahmed** [comment]
i use the code you give but when print the brand in view it's print the entire function as a string 

![image](https://github.com/adonisjs/view/assets/25245905/b626593b-19ae-4cdd-8d35-c9ad50e4a46f)

![image](https://github.com/adonisjs/view/assets/25245905/96faca0c-e57b-42ce-a839-0af17a203d07)

Our Put

![image](https://github.com/adonisjs/view/assets/25245905/6fab441f-2d8f-4359-8714-97f1e988fb7d)


```typescript

    function () {
            return Brand_1.default.first();
        }

    
```

**Comment by RomainLanz** [comment]
It is a function, you have to call it.

**Comment by jualahmed** [comment]
it's return a [object Promise] . how to resolve the Promise before page load?

**Comment by thetutlage** [comment]
@jualahmed Same as you call a method that is async.

Also, this is not related to the library, please use discussion forum or Stackoverflow to ask such questions
