### ISSUE TITLE
ctx.resolve is not a function when including assets

### ISSUE THREAD

**Issue by carlosero** [adonisjs/view#4]
## Package version
1.0.13

## Node.js and npm version
$ node -v
v12.16.2
$ npm -v
6.14.4

## Sample Code (to reproduce the issue)
- Create new app with `npx create-adonis-ts-app`
- Select "Web Application" during initialization, leave rest as default
- cd test
- Edit file resources/views/welcome.edge
  - In line 8, add `{{ script("https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js") }}`
- Run server `node ace serve --watch`, go to localhost:3333
- Following error shows:
![image](https://user-images.githubusercontent.com/2349502/79091607-dc30dc00-7d1b-11ea-8e21-f4efafa42e27.png)

## BONUS (a sample repo to reproduce the issue)
https://github.com/carlosero/adonis-test

Already checked all closed issues and main repo's (adonisjs), including #3, but nothing related found. Happens with both `style` and `script`, and happens with both local and remote (url) files.

**Comment by RomainLanz** [comment]
Hey @carlosero! 👋 

Those methods doesn't exists in V5 because they are not usefull.
Use directly a `<script src="..."></script>" or "<link />" tag to import your resource.

**Comment by carlosero** [comment]
I see, how do I import local assets? Let's say I have public/js with a file called test.js, how would I import it
