### ISSUE TITLE
Incorrect Unicode parsing attempt on Windows

### ISSUE THREAD

**Issue by woubuc** [adonisjs/view#5]
## Versions
- `@adonisjs/core` v5.0.0-preview.5
- `@adonisjs/view` v1.0.13
- Node v12.14.1
- Npm v6.13.4

## Problem
When rendering a view, the library will attempt to parse Unicode values in the path when they contain `\u`. This happens for all files or directories starting with the letter `u` on Windows platforms, which uses the `\` path separator.

## Steps to Reproduce
- Create an empty view named `user.edge`
- Add a route `Route.on('/test').render('user')` to your router
- Try to load this route `/test` in your browser
- You will see an error page with the message `Invalid Unicode escape sequence`

**Comment by thetutlage** [comment]
Can you share the template that has `\u` unicode for me to reproduce the issue?

**Comment by woubuc** [comment]
It happens with any template with a filename that starts with the letter `u`. So even just an empty template file named `u.edge` will error on Windows, because the resolved path to it will be `views\u.edge` which contains the `\u` that the Unicode parser tries to parse.

This problem doesn't happen on Unix-based platforms because they use `/` as a path separator, so the resolved path ends up being `views/u.edge` which doesn't contain a `\u` escape sequence.

**Comment by thetutlage** [comment]
Can you share the complete error stack?

**Comment by woubuc** [comment]
```
SyntaxError: Invalid Unicode escape sequence

[project root]\node_modules\edge.js\build\src\Template\index.js:65:16
Template.render
[project root]\node_modules\edge.js\build\src\Renderer\index.js:35:25
EdgeRenderer.render
[project root]\node_modules\@adonisjs\view\build\providers\ViewProvider.js:66:29
Object.handler
[project root]\node_modules\@adonisjs\http-server\build\src\Server\PreCompiler\index.js:48:54
PreCompiler.finalRouteHandler
[project root]\node_modules\co-compose\build\src\Runnable.js:48:47
Runnable.invoke
[project root]\node_modules\@adonisjs\bodyparser\build\src\BodyParser\index.js:92:20
BodyParserMiddleware.handle
[project root]\node_modules\@adonisjs\fold\build\src\Ioc\Injector.js:68:30
Injector.injectMethodDependencies
[project root]\node_modules\@adonisjs\fold\build\src\Ioc\index.js:543:30
Ioc.call
[project root]\node_modules\@adonisjs\fold\build\src\Resolver\index.js:102:31
IocResolver.call 
```

I've also pushed a repo that contains the blank project setup with just the `u.edge` empty template to reproduce the error. https://github.com/woubuc/adonisjs-unicode-error-repr

**Comment by thetutlage** [comment]
Thanks. Looking into it

**Comment by thetutlage** [comment]
Will be fixed in next release of this module.
